const router = require('express').Router();
const ctrl = require('../controllers/notificationController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/', ctrl.getAll);
router.get('/unread-count', ctrl.unreadCount);
router.patch('/mark-all-read', ctrl.markAllRead);
router.patch('/:id/read', ctrl.markRead);
router.delete('/:id', ctrl.remove);
module.exports = router;
