const router = require('express').Router();
const ctrl = require('../controllers/analyticsController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/monthly-spend', ctrl.monthlySpend);
router.get('/category-breakdown', ctrl.categoryBreakdown);
router.get('/forecast', ctrl.forecast);
router.get('/renewal-calendar', ctrl.renewalCalendar);
router.get('/top-subscriptions', ctrl.topSubscriptions);
module.exports = router;
