const router = require('express').Router();
const ctrl = require('../controllers/subscriptionController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/summary', ctrl.getSummary);
router.get('/upcoming', ctrl.getUpcoming);
router.post('/bulk-import', ctrl.bulkImport);
router.route('/').get(ctrl.getAll).post(ctrl.create);
router.route('/:id').get(ctrl.getOne).put(ctrl.update).delete(ctrl.remove);
router.patch('/:id/status', ctrl.updateStatus);
module.exports = router;
